helmDefaults:
  wait: true
  timeout: 600
  atomic: true
  createNamespace: true

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
releases:
  # Prometheus
  - name: prometheus
    namespace: observability
    chart: prometheus-community/prometheus
    values:
      - values/prometheus-values.yaml
