helmDefaults:
  wait: true
  timeout: 600
  atomic: true
  createNamespace: true

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # Prometheus
  - name: prometheus
    namespace: observability
    chart: prometheus-community/prometheus
    values:
      - values/prometheus-values.yaml

  # Grafana
  - name: grafana
    namespace: observability
    chart: grafana/grafana
    values:
      - values/grafana-values.yaml

  # Elasticsearch
  - name: elasticsearch
    namespace: observability
    chart: elastic/elasticsearch
    values:
      - values/elasticsearch-values.yaml

  # Kibana
  - name: kibana
    namespace: observability
    chart: elastic/kibana
    values:
      - values/kibana-values.yaml
    needs:
      - observability/elasticsearch

  # Fluent Bit
  - name: fluent-bit
    namespace: observability
    chart: fluent/fluent-bit
    values:
      - values/fluent-bit-values.yaml
    needs:
      - observability/elasticsearch

  # Sample app: podinfo
  - name: podinfo
    namespace: demo
    chart: podinfo/podinfo
    values:
      - values/podinfo-values.yaml
