helmDefaults:
  wait: true
  timeout: 600
  atomic: true
  createNamespace: true

repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: opensearch
    url: https://opensearch-project.github.io/helm-charts
  - name: fluent
    url: https://fluent.github.io/helm-charts
  - name: jaegertracing
    url: https://jaegertracing.github.io/helm-charts
  - name: podinfo
    url: https://stefanprodan.github.io/podinfo

releases:
  # Prometheus
  - name: prometheus
    namespace: observability
    chart: prometheus-community/prometheus
    values:
      - values/prometheus-values.yaml

  # Grafana
  - name: grafana
    namespace: observability
    chart: grafana/grafana
    values:
      - values/grafana-values.yaml

  # OpenSearch
  - name: opensearch
    namespace: observability
    chart: opensearch/opensearch
    values:
      - values/opensearch-values.yaml

  # OpenSearch Dashboards
  - name: opensearch-dashboards
    namespace: observability
    chart: opensearch/opensearch-dashboards
    values:
      - values/opensearch-dashboards-values.yaml
    needs:
      - observability/opensearch

  # Fluent Bit
  - name: fluent-bit
    namespace: observability
    chart: fluent/fluent-bit
    values:
      - values/fluent-bit-values.yaml
    needs:
      - observability/opensearch

  # Jaeger
  - name: jaeger
    namespace: observability
    chart: jaegertracing/jaeger
    values:
      - values/jaeger-values.yaml

  # Sample app: podinfo backend
  - name: podinfo-backend
    namespace: demo
    chart: podinfo/podinfo
    values:
      - values/podinfo-backend-values.yaml

  # Sample app: podinfo frontend
  - name: podinfo-frontend
    namespace: demo
    chart: podinfo/podinfo
    values:
      - values/podinfo-frontend-values.yaml
    needs:
      - demo/podinfo-backend
