#!/bin/bash

# Script to send a test alert to Alertmanager for testing
# Usage: ./scripts/test-alert.sh [alertname] [severity]

set -e

ALERTNAME="${1:-TestAlert}"
SEVERITY="${2:-warning}"
ALERTMANAGER_URL="${ALERTMANAGER_URL:-http://localhost:9093}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Alertmanager Test Alert${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Alert Name: $ALERTNAME"
echo "Severity: $SEVERITY"
echo "Target: $ALERTMANAGER_URL"
echo ""

# Create alert payload
ALERT_PAYLOAD=$(cat <<EOF
[{
  "labels": {
    "alertname": "$ALERTNAME",
    "severity": "$SEVERITY",
    "service": "test-script",
    "namespace": "observability"
  },
  "annotations": {
    "summary": "Test alert generated by test-alert.sh",
    "description": "This is a test alert with severity $SEVERITY. It will auto-resolve after the timeout period."
  },
  "startsAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "generatorURL": "http://localhost:9090/graph"
}]
EOF
)

# Send alert
echo -e "${YELLOW}Sending test alert to Alertmanager...${NC}"
RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
  -H "Content-Type: application/json" \
  -d "$ALERT_PAYLOAD" \
  "$ALERTMANAGER_URL/api/v1/alerts")

HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
RESPONSE_BODY=$(echo "$RESPONSE" | sed '$d')

if [ "$HTTP_CODE" = "200" ]; then
    echo -e "${GREEN}✓ Test alert sent successfully!${NC}"
    echo ""
    echo "View the alert at: $ALERTMANAGER_URL"
    echo ""
    echo "Or query via API:"
    echo "  curl -s $ALERTMANAGER_URL/api/v2/alerts | jq '.'"
    echo ""
else
    echo -e "${RED}✗ Failed to send alert (HTTP $HTTP_CODE)${NC}"
    echo "Response: $RESPONSE_BODY"
    exit 1
fi
